pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: node
    image: node:22-alpine
    command: ['cat']
    tty: true
    volumeMounts:
    - name: npm-cache
      mountPath: /root/.npm
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ['cat']
    tty: true
    volumeMounts:
    - name: kaniko-cache
      mountPath: /cache
  - name: argocd
    image: quay.io/argoproj/argocd:v2.13.0
    command: ['cat']
    tty: true
  volumes:
  - name: npm-cache
    emptyDir: {}
  - name: kaniko-cache
    emptyDir: {}
"""
    }
  }

  environment {
    APP_NAME   = "tahirefendii/tahir-basic-nodejs-project"
    IMAGE_TAG  = "${env.BUILD_NUMBER}"
    IMAGE      = "docker.io/${APP_NAME}:${IMAGE_TAG}"
    ARGOCD_APP = "my-nodejs-app"
    ARGOCD_SRV = "argocd-server.argocd.svc.cluster.local:443"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install') {
      steps {
        container('node') {
          sh 'echo "Hello, i am creating a container"'
          sh 'node -v && npm -v'
          sh 'npm ci || npm install'
        }
      }
    }

    stage('Build app') {
      when {
        expression { fileExists('package.json') }
      }
      steps {
        container('node') {
          sh 'npm run build || echo "no build step"'
        }
      }
    }

    stage('Build & Push (kaniko)') {
      steps {
        container('kaniko') {
          withCredentials([usernamePassword(
            credentialsId: 'docker-registry',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PWD'
          )]) {
            writeFile file: 'docker-config.json', text: """{
  "auths": {
    "https://index.docker.io/v1/": {
      "username": "${DOCKER_USER}",
      "password": "${DOCKER_PWD}"
    }
  }
}"""
            sh '''
              set -eux

              mkdir -p /kaniko/.docker
              cp docker-config.json /kaniko/.docker/config.json

              /kaniko/executor \
                --context "$(pwd)" \
                --dockerfile Dockerfile \
                --destination "$IMAGE" \
                --cache=true \
                --cache-dir=/cache
            '''
          }
        }
      }
    }

    stage('Update ArgoCD') {
      steps {
        timeout(time: 2, unit: 'MINUTES') {
          container('argocd') {
            withCredentials([usernamePassword(
              credentialsId: 'argocd',           // Jenkins'teki ArgoCD cred ID
              usernameVariable: 'ARGOCD_USER',
              passwordVariable: 'ARGOCD_PASS'
            )]) {
              sh 'echo "Hello from argocd container"'
            }
          }
        }
      }
    }
  }

  post {
    success {
      echo "Image pushed: ${IMAGE}"
    }
    failure {
      echo "Pipeline failed"
    }
  }
}
